module.exports = {
		'MISSING_SECTION': 'MISSING_SECTION',
		'WRONG_HEADER_FOR_SECTION' : 'WRONG_HEADER_FOR_SECTION',
		'INVALID_SECTION_TYPE': 'INVALID_SECTION_TYPE',
		'INVALID_SCHEMA': 'INVALID_SCHEMA',
		'MISSING_TITLE': 'MISSING_TITLE'
};